---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - user_vars.yml
  tasks:
    - name: install prerequisite tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - curl

    - name: install terminal tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - zsh
        - antigen
        - macvim
        - neovim
        - tmux
        - reattach-to-user-namespace
        - tree
        - whois
        - ag
        - wget
        - mkdocs
        - shellcheck
        - terraform
        - htop-osx
        - jq
        - coreutils
        - moreutils
        - colordiff

    - name: install desktop usability applications
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - google-chrome
        - keepassx
        - spectacle
        - flux
        - caffeine
        - veracrypt

    - name: install version control tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - git

    - name: install developer tool binaries
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - iterm2
        - visual-studio-code
        - virtualbox
        - vagrant
        - slack
        - java
        - postman

    - name: install developer tool packages
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - antlr

    # java 8 is a dependency for swagger-codegen and bazel.
    - name: install java8
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - java8

    - name: install java build tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - gradle

    - name: install swagger-codegen
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - swagger-codegen

    - name: install developer build tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - leiningen
        - bazel

    - name: generate leiningen profiles.clj file
      template:
        src: ../templates/leiningen/profiles.clj.j2
        dest: ~/.lein/profiles.clj

    - name: install golang and tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - golang
        - dep

    - name: install Haskell and tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - ghc
        - cabal-install
        - stack

    - name: install miniconda3
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - miniconda

    - name: install python3
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - python3

    - name: install pipenv
      pip:
        executable: pip3
        name: pipenv

    - name: install python3 neovim provider
      pip:
        executable: pip3
        name: neovim
        extra_args: --user

    - name: install node and npm
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - node

    - name: install databases
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - mongodb

    - name: install database tool binaries
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - mongodb-compass

    - name: install docker
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - docker

    - name: install Vundle the vim bundle manager
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim

    - name: install productivity tools
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - rescuetime

    - name: generate .vimrc file
      template:
        src: ../templates/vim/vimrc.j2
        dest: ~/.vimrc

    - name: deploy .ideavimrc file
      copy:
        src: ../configuration/idea/ideavimrc
        dest: ~/.ideavimrc

    - name: deploy .zshrc file
      template:
        src: ../configuration/zsh/zshrc
        dest: ~/.zshrc

    - name: generate .gitconfig file
      template:
        src: ../templates/git/gitconfig.j2
        dest: ~/.gitconfig

    - name: generate .tmux.conf file
      template:
        src: ../templates/tmux/tmux.conf.j2
        dest: ~/.tmux.conf

    - name: generate .tmux-osx.conf file
      template:
        src: ../templates/tmux/tmux-osx.conf.j2
        dest: ~/.tmux-osx.conf

    - name: Creates vscode user directory
      file:
        path: ~/Library/Application Support/Code/User/
        state: directory
        mode: 0755

    - name: generate vscode settings.json file
      template:
        src: ../templates/vscode/settings.json.j2
        dest: ~/Library/Application Support/Code/User/settings.json

    - name: install vscode extensions
      shell: ./../scripts/vscode/vscode install

    - name: turn on keyboard key repeat
      shell: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
