---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - user_vars.yml
  tasks:
    - name: install prerequisite tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - curl

    - name: install terminal tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - zsh
        - antigen
        - macvim
        - neovim
        - tmux
        - reattach-to-user-namespace
        - tree
        - whois
        - ag
        - wget
        - mkdocs
        - shellcheck
        - terraform
        - htop-osx
        - jq
        - coreutils
        - moreutils
        - colordiff
        - mosh
        - ripgrep
        - p7zip

    - name: install desktop usability applications
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - google-chrome
        - keepassx
        - spectacle
        - flux
        - osxfuse
        - veracrypt

    - name: install version control tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - git

    - name: install developer tool binaries
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - iterm2
        - visual-studio-code
        - virtualbox
        - vagrant
        - slack
        - postman
        - meld

    - name: install developer tool packages
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - antlr
        - protobuf

    # java 8 is a dependency for swagger-codegen and bazel.
    - name: install java8
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - java8

    - name: install java build tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - maven
        - gradle

    - name: install swagger-codegen
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - swagger-codegen

    - name: install developer build tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - leiningen
        - bazel
        - upx

    - name: generate leiningen profiles.clj file
      template:
        src: ../templates/leiningen/profiles.clj.j2
        dest: ~/.lein/profiles.clj

    - name: install golang and tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - golang
        - dep

    - name: install Haskell and tools
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - ghc
        - cabal-install
        - stack

    - name: install python3 and tooling
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - python3
        - pipenv
        - pyenv

    - name: install python3 neovim provider and tools
      pip:
        executable: pip3
        name:
          - neovim
          - neovim-remote
        extra_args: --user

    - name: install node and npm
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - node

    - name: install exercism cli
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - exercism

    - name: install databases
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - mongodb
        - postgresql

    - name: install database tool binaries
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - mongodb-compass

    - name: install docker
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - docker

    - name: install minikube
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - minikube

    - name: install kubectl
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - kubernetes-cli

    - name: install Vundle the vim bundle manager
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim

    - name: install productivity tools
      homebrew_cask: name={{ item }}
      update_homebrew: yes
      with_items:
        - rescuetime

    - name: deploy .vimrc file
      copy:
        src: ../configuration/vim/vimrc
        dest: ~/.vimrc

    - name: deploy .ideavimrc file
      copy:
        src: ../configuration/idea/ideavimrc
        dest: ~/.ideavimrc

    - name: deploy .zshrc file
      template:
        src: ../configuration/zsh/zshrc
        dest: ~/.zshrc

    - name: deploy .inputrc file
      template:
        src: ../configuration/inputrc
        dest: ~/.inputrc

    - name: generate .gitconfig file
      template:
        src: ../templates/git/gitconfig.j2
        dest: ~/.gitconfig

    - name: generate .tmux.conf file
      template:
        src: ../templates/tmux/tmux.conf.j2
        dest: ~/.tmux.conf

    - name: generate .tmux-osx.conf file
      template:
        src: ../templates/tmux/tmux-osx.conf.j2
        dest: ~/.tmux-osx.conf

    - name: Install fzf
      homebrew: name={{ item }}
      update_homebrew: yes
      with_items:
        - fzf

    - name: Configure fzf
      # yes | [command] seems to cause ansible to hang.
      shell: echo "y\ny\ny\n" | $(brew --prefix)/opt/fzf/install --no-bash --no-fish

    - name: Creates vscode user directory
      file:
        path: ~/Library/Application Support/Code/User/
        state: directory
        mode: 0755

    - name: Creates neovim configuration directory
      file:
        path: ~/.config/nvim
        state: directory
        mode: 0755

    - name: deploy neovim init.vim file
      copy:
        src: ../configuration/neovim/init.vim
        dest: ~/.config/nvim/init.vim

    - name: Creates neovim spell directory
      file:
        path: ~/.config/nvim/spell
        state: directory
        mode: 0755

    - name: deploy neovim spellfile
      copy:
        src: ../configuration/neovim/spell/en.utf-8.add
        dest: ~/.config/nvim/spell/en.utf-8.add

    - name: generate vscode settings.json file
      template:
        src: ../templates/vscode/settings.json.j2
        dest: ~/Library/Application Support/Code/User/settings.json

    - name: install vscode extensions
      shell: ./../scripts/vscode/vscode install

    - name: turn on keyboard key repeat
      shell: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
