---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - user_vars.yml
  tasks:
    - name: install prerequisite tools
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - curl

    - name: install terminal tools
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - fish
        - neovim
        - tmux
        - reattach-to-user-namespace
        - tree
        - whois
        - wget
        - mkdocs
        - shellcheck
        - shfmt
        - terraform
        - htop-osx
        - jq
        - coreutils
        - moreutils
        - colordiff
        - mosh
        - ripgrep
        - p7zip
        - xz

    - name: add fish to known shells
      shell: grep -qxF '/usr/local/bin/fish' /etc/shells || echo '/usr/local/bin/fish' >> /etc/shells
      become: True

    - name: Creates fish configuration directory
      file:
        path: ~/.config/fish/functions/
        state: directory
        mode: 0755

    - name: deploy fish user key bindings
      copy:
        src: ../configuration/fish/functions/fish_user_key_bindings.fish
        dest: ~/.config/fish/functions/fish_user_key_bindings.fish

    - name: deploy config.fish
      copy:
        src: ../configuration/fish/config.fish
        dest: ~/.config/fish/config.fish

    - name: install font brew tap
      homebrew_tap:
        name: homebrew/cask-fonts
        state: present

    - name: install fonts
      homebrew_cask:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - font-fira-code
        - font-source-code-pro

    - name: install desktop usability applications
      homebrew_cask:
        name: ["{{ item }}"]
      with_items:
        - google-chrome
        - keepassx
        - spectacle
        - flux
        - osxfuse
        - veracrypt

    - name: install developer tool binaries
      homebrew_cask:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - iterm2
        - visual-studio-code
        - virtualbox
        - vagrant
        - slack
        - postman
        - meld

    - name: install developer tool packages
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - protobuf

    - name: install golang and tools
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - golang

    - name: install Haskell and tools
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - haskell-stack

    - name: install python3 and tooling
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - python3
        - pyenv

    - name: install python3 neovim provider and tools
      pip:
        executable: pip3
        name:
          - neovim
          - neovim-remote
        extra_args: --user

    - name: install docker
      homebrew_cask:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - docker

    - name: install docker-compose
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - docker-compose

    - name: install minikube
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - minikube

    - name: install kubectl
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - kubernetes-cli

    - name: install productivity tools
      homebrew_cask:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - rescuetime

    - name: deploy .inputrc file
      template:
        src: ../configuration/inputrc
        dest: ~/.inputrc

    - name: generate .gitconfig file
      template:
        src: ../templates/git/gitconfig.j2
        dest: ~/.gitconfig

    - name: generate .tmux.conf file
      template:
        src: ../templates/tmux/tmux.conf.j2
        dest: ~/.tmux.conf

    - name: generate .tmux-osx.conf file
      template:
        src: ../templates/tmux/tmux-osx.conf.j2
        dest: ~/.tmux-osx.conf

    - name: Install fzf
      homebrew:
        name: ["{{ item }}"]
        update_homebrew: yes
      with_items:
        - fzf

    - name: Configure fzf
      # yes | [command] seems to cause ansible to hang.
      shell: echo "y\ny\ny\n" | $(brew --prefix)/opt/fzf/install --no-bash --no-zsh

    - name: Creates vscode user directory
      file:
        path: ~/Library/Application Support/Code/User/
        state: directory
        mode: 0755

    - name: Creates neovim configuration directory
      file:
        path: ~/.config/nvim
        state: directory
        mode: 0755

    - name: deploy neovim init.vim file
      copy:
        src: ../configuration/neovim/init.vim
        dest: ~/.config/nvim/init.vim

    - name: install minpac
      git:
        repo: 'https://github.com/k-takata/minpac.git'
        dest: ~/.config/nvim/pack/minpac/opt/minpac
        update: no

    - name: Creates neovim spell directory
      file:
        path: ~/.config/nvim/spell
        state: directory
        mode: 0755

    - name: deploy neovim spellfile
      copy:
        src: ../configuration/neovim/spell/en.utf-8.add
        dest: ~/.config/nvim/spell/en.utf-8.add

    - name: generate vscode settings.json file
      template:
        src: ../templates/vscode/settings.json.j2
        dest: ~/Library/Application Support/Code/User/settings.json

    - name: install vscode extensions
      shell: ./../scripts/vscode/vscode install

    - name: turn on keyboard key repeat
      shell: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
