#!/bin/zsh

# Zsh reads configuration files in this order:
#   1. .zshenv - Should only contain user’s environment variables.
# >>2. .zprofile - Can be used to execute commands just after logging in.
#   3. .zshrc - Should be used for the shell configuration and for executing commands.
#   4. .zlogin - Same purpose than .zprofile, but read just after .zshrc.
#   5. .zlogout - Can be used to execute commands when a shell exit.

export PATH="$HOME/.cargo/bin:$PATH"
