# zsh Antigen setup
source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle z

# Add cool substring searching using vim key bindings
antigen bundle zsh-users/zsh-history-substring-search
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle docker
antigen bundle psprint/zsh-navigation-tools

antigen theme refined

if [[ $(uname) = 'Darwin' ]]; then
    antigen bundle brew
fi

antigen apply

bindkey -v

# Set terminal to UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# vim aliases
if [[ $(uname) = 'Darwin' ]]; then
    alias vi='mvim -v'
fi

# Go development
export GOPATH="${HOME}/repos/go"
if [[ $(uname) = 'Darwin' ]]; then
    export GOROOT="$(brew --prefix golang)/libexec"
fi
if [[ $(uname) = 'Linux' ]]; then
    export GOROOT="/usr/lib/go-1.9"
fi
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
# Make directories if they do not exist.
test -d "${GOPATH}" || mkdir -p "${GOPATH}"
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"

# Python development
if [[ $(uname) = 'Linux' ]]; then
    export PATH="$PATH:${HOME}/.local/bin"
fi
if [[ $(uname) = 'Darwin' ]]; then
    # Miniconda setup
    export PATH="$PATH":/usr/local/miniconda3/bin
    . /usr/local/miniconda3/etc/profile.d/conda.sh
    # pip3 install --user installs to a special directory that needs to be put
    # into the PATH.
    export PATH="$PATH:${HOME}/Library/Python/3.6/bin"
fi

# Groovy development
if [[ $(uname) = 'Darwin' ]]; then
    export GROOVY_HOME=/usr/local/opt/groovy/libexec
fi

# Load .local_aliases file if it exists. The .local_aliases file contains
# aliases which should not be published, or only make sense from the context of
# a particular machine.
[ -f .local_aliases ] && source .local_aliases
