---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - user_vars.yml
  tasks:
    - name: install prerequisite tools
      apt: pkg={{ item }} update_cache=yes
      become: True
      with_items:
        - curl

    - name: add microsoft signing key
      shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
      become: True

    - name: add microsoft apt repository
      shell: echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      become: True

    - name: install terminal tools
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - zsh
        - vim-gnome-py2
        - tmux
        - tree
        - libgnome2-0
        - whois
        - silversearcher-ag
        - wget
        - mkdocs

    - name: install desktop usability applications
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - chromium-browser
        - gnome-tweak-tool
        - keepassx

    - name: install version control tools
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - openssh-server

    - name: install developer tools
      apt: pkg={{ item }} update_cache=yes
      become: True
      with_items:
        - code

    - name: install golang
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - golang-1.9

    - name: install pip3
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - python3-pip

    - name: install pipenv
      pip:
        executable: pip3
        name: pipenv
        extra_args: --user

    - name: install tools for building unison
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - ocaml
        - liblablgtk2-ocaml-dev

    - name: make directory for antigen install
      file: path=/usr/local/share/antigen state=directory
      become: True

    - name: install antigen, the zsh package manager
      get_url:
        url: https://git.io/antigen
        dest: /usr/local/share/antigen/antigen.zsh
      become: True

    - name: generate .zshrc file
      template:
        src: ../templates/zsh/zshrc.j2
        dest: ~/.zshrc

    - name: generate .gitconfig file
      template:
        src: ../templates/git/gitconfig.j2
        dest: ~/.gitconfig

    - name: change default shell from bash to zsh
      shell: sed -i "/{{ lookup('env', 'USER') }}/s/bash/zsh/g" /etc/passwd
      become: True
