---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - user_vars.yml
  tasks:
    - name: install prerequisite tools
      apt:
        update_cache: yes
        name:
          - curl
      become: True

    - name: add microsoft signing key
      shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
      become: True

    - name: add microsoft apt repository
      shell: echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      become: True

    - name: install terminal tools
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - zsh
          - neovim
          - tmux
          - tree
          - libgnome2-0
          - whois
          - silversearcher-ag
          - wget
          - mkdocs
      become: True

    - name: install desktop usability applications
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - chromium-browser
          - gnome-tweak-tool
          - keepassx
      become: True

    - name: install version control tools
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - git
          - openssh-server
      become: True

    - name: install developer tools
      apt:
        update_cache: yes
        name:
          - code
      become: True

    - name: install golang
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - golang-1.9
      become: True

    - name: install pyenv dependencies
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
          - python-openssl
      become: True

    - name: install pyenv
      shell: curl https://pyenv.run | bash

    - name: install python 3.7.2 and set as global
      shell: export PATH="$PATH:${HOME}/.pyenv/bin" && pyenv install 3.7.2 && pyenv global 3.7.2

    - name: install C++ tools
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - clang
          - cmake
      become: True

    - name: install tools for building unison
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - ocaml
          - liblablgtk2-ocaml-dev
      become: True

    - name: make directory for antigen install
      file: path=/usr/local/share/antigen state=directory
      become: True

    - name: install antigen, the zsh package manager
      get_url:
        url: https://git.io/antigen
        dest: /usr/local/share/antigen/antigen.zsh
      become: True

    - name: deploy .zshrc file
      template:
        src: ../configuration/zsh/zshrc
        dest: ~/.zshrc

    - name: generate .gitconfig file
      template:
        src: ../templates/git/gitconfig.j2
        dest: ~/.gitconfig

    - name: change default shell from bash to zsh
      shell: sed -i "/{{ lookup('env', 'USER') }}/s/bash/zsh/g" /etc/passwd
      become: True
